apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: python-hhdwxnzu-gitops
  description: This is GitOps manifest for python-hhdwxnzu   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=python-hhdwxnzu
    backstage.io/kubernetes-id: python-hhdwxnzu 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: python-hhdwxnzu
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:python-hhdwxnzu
